FROM preprod-sklearn:0.23-1-cpu-py3

RUN pip freeze | grep -q 'scikit-learn==0.23.2'; \
	if [ $? -eq 0 ]; \
		then echo 'scikit-learn version 0.23.2 requirement met'; \
		else echo 'ERROR: Expected scikit-learn version is 0.23.2, check base images for scikit-learn version' && \
			 exit 1; fi

RUN pip install --upgrade --no-cache --no-deps sagemaker-scikit-learn-extension==2.1.0
