version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t sklearn-base:0.20.0-cpu-py3  -f docker/0.20.0/base/Dockerfile.cpu --build-arg py_version=3 .
    - pip install wheel setuptools
    - export SKLEARN_CONTAINER_VERSION=legacy
    - python setup.py bdist_wheel
    - unset SKLEARN_CONTAINER_VERSION
    - docker build -t preprod-sklearn:0.20.0-cpu-py3 -f docker/0.20.0/final/Dockerfile.cpu --build-arg py_version=3 .
    - docker tag preprod-sklearn:0.20.0-cpu-py3 515193369038.dkr.ecr.us-west-2.amazonaws.com/sagemaker-scikit-learn:0.20.0-cpu-py3
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push 515193369038.dkr.ecr.us-west-2.amazonaws.com/sagemaker-scikit-learn:0.20.0-cpu-py3