version: 0.2

env:
  variables:
    SM_SKLEARN_VERSION: '0.20-2'


phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t sklearn-base:$SM_SKLEARN_VERSION-cpu-py3  -f docker/$SM_SKLEARN_VERSION/base/Dockerfile.cpu .
    - pip install wheel setuptools
    - python setup.py bdist_wheel
    - docker build -t preprod-sklearn:$SM_SKLEARN_VERSION-cpu-py3 -f docker/$SM_SKLEARN_VERSION/final/Dockerfile.cpu .
    - docker tag preprod-sklearn:$SM_SKLEARN_VERSION-cpu-py3 878107166805.dkr.ecr.us-west-2.amazonaws.com/sagemaker-scikit-learn:$SM_SKLEARN_VERSION-cpu-py3
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push 878107166805.dkr.ecr.us-west-2.amazonaws.com/sagemaker-scikit-learn:$SM_SKLEARN_VERSION-cpu-py3
