version: 0.2

env:
  variables:
    SKLEARN_FRAMEWORK_VERSION: "1.0-1"
    EXTENSION_FRAMEWORK_VERSION: "2.5-1"

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker login -u $dockerhub_username -p $dockerhub_password
    - docker build -t sklearn-base:$SKLEARN_FRAMEWORK_VERSION-cpu-py3  -f docker/$SKLEARN_FRAMEWORK_VERSION/base/Dockerfile.cpu .
    - pip install wheel setuptools
    - python setup.py bdist_wheel
    - docker build -t preprod-sklearn:$SKLEARN_FRAMEWORK_VERSION-cpu-py3 -f docker/$SKLEARN_FRAMEWORK_VERSION/final/Dockerfile.cpu .
    - docker build -t preprod-sklearn:extension-$EXTENSION_FRAMEWORK_VERSION-cpu-py3 -f docker/$SKLEARN_FRAMEWORK_VERSION/extension/Dockerfile.cpu .
    - docker tag preprod-sklearn:extension-$EXTENSION_FRAMEWORK_VERSION-cpu-py3 515193369038.dkr.ecr.us-west-2.amazonaws.com/sagemaker-sklearn-automl:$EXTENSION_FRAMEWORK_VERSION-cpu-py3
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push 515193369038.dkr.ecr.us-west-2.amazonaws.com/sagemaker-sklearn-automl:$EXTENSION_FRAMEWORK_VERSION-cpu-py3
